services:
  - docker

jobs:
  include:
    - stage: build
      language: minimal
      script:
        - docker build . -t shu-student-course
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag shu-student-course $DOCKER_USERNAME/shu-student-course:latest
        - docker push $DOCKER_USERNAME/shu-student-course
